server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        rewrite ^ /pages/index/index.html last;
    }

    location / {
        try_files $uri $uri/ /pages/index/index.html;
    }

    location /pages/ {
        try_files $uri $uri/ =404;
    }

    location /css/ {
        try_files $uri =404;
    }

    location /src/ {
        try_files $uri =404;
    }
}